/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.DBConnection;

/**
 *
 * @author 33760
 */
public class ConnexionM extends javax.swing.JFrame {

     Connection con = null;
    PreparedStatement pst = null;

    
    /**
     * Creates new form ConnexionM
     */
    public ConnexionM() {
        initComponents();
    }

    void verificationUtilisateur(String mail, String motDePass){
        try{
            String sql = "SELECT idmembre, mail, motDePass FROM membre WHERE mail=? AND motDePass = ?";
            con = DBConnection.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, mail);
            pst.setString(2, motDePass);
           
            
            ResultSet rs = pst.executeQuery();
            
            if(rs.next()){
               JOptionPane.showMessageDialog(this, "connexion réussie");
               FMenuMembre membre = new FMenuMembre(rs.getInt("idmembre"));
               membre.setVisible(true);
               membre.pack();
               membre.idMembre = rs.getInt("idmembre");
                System.out.println(rs.getInt("idmembre"));
               this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "mail OU mot de passe incorrects");
            }
        }catch(Exception e){
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtidentifiant = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        bntConnect = new javax.swing.JButton();
        btnInsc = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel3.setText("Mot de passe");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel4.setText("Identifiant");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, -1));

        txtidentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidentifiantActionPerformed(evt);
            }
        });
        jPanel1.add(txtidentifiant, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 210, 40));
        jPanel1.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 210, 40));

        btnExit.setBackground(new java.awt.Color(0, 51, 153));
        btnExit.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExit.setText("Quitter");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, -1));

        bntConnect.setBackground(new java.awt.Color(0, 51, 153));
        bntConnect.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        bntConnect.setForeground(new java.awt.Color(255, 255, 255));
        bntConnect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        bntConnect.setText("Se connecter");
        bntConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConnectActionPerformed(evt);
            }
        });
        jPanel1.add(bntConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, 40));

        btnInsc.setBackground(new java.awt.Color(0, 51, 153));
        btnInsc.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnInsc.setForeground(new java.awt.Color(255, 255, 255));
        btnInsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signup.png"))); // NOI18N
        btnInsc.setText("S'inscrire");
        btnInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 520, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 730, 420));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Connexion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 100));

        setSize(new java.awt.Dimension(636, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtidentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidentifiantActionPerformed

    private void bntConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConnectActionPerformed
        // TODO add your handling code here:
        String identfiant = txtidentifiant.getText();
        String password = txtPwd.getText();
        
        if(identfiant.trim().equals("") || password.trim().equals("")){
            lblError.setText("Veuillez entrez vos identifiants s'il vous plaît ");
        }else{
            verificationUtilisateur(identfiant, password);
        }
    }//GEN-LAST:event_bntConnectActionPerformed

    private void btnInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscActionPerformed
        // TODO add your handling code here:
        InscriptionMembre inscription = new InscriptionMembre();
        inscription.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnInscActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Index accueil = new Index();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConnexionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConnexionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConnexionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConnexionM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConnexionM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConnect;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblError;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtidentifiant;
    // End of variables declaration//GEN-END:variables
}
