/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import model.DBConnection;

/**
 *
 * @author 33760
 */
public class Admin extends javax.swing.JFrame {
     Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        remplirRole();
    }
    
    
    public void remplirRole() {
       try{
            String sql = "SELECT role FROM administrateur";
        con = DBConnection.getConnection();
        pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
        
        while(rs.next()){
            String role = rs.getString("role").toString();
            jcombRole.addItem(role);
        }
        con.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, "");
       }
    }
    
    
    public void verificationUtilisateur(String identfiant, String password, String role){
        try{
            String sql = "SELECT mail, MotDePass FROM administrateur WHERE mail=? AND motDePass = ? AND role = ?";
            con = DBConnection.getConnection();
            pst = con.prepareStatement(sql);
            pst.setString(1, identfiant);
            pst.setString(2, password);
            pst.setString(3, role);
            rs = pst.executeQuery();
            
             if(rs.next()){
               JOptionPane.showMessageDialog(this, "identifiants corrects. Vous êtes connecté en tant que " + role);
                if (role.equals("Service Juridique")){
                    FMenuServJurid juridique = new FMenuServJurid();
                    juridique.setVisible(true);
                    this.dispose();
                }else if(role.equals("Gestionnaire Site")){
                    FMenuGestionSite gestionnaire = new FMenuGestionSite();
                    gestionnaire.setVisible(true);
                    this.dispose();
                }else {
                    FMenuServCom commercial = new FMenuServCom();
                    commercial.setVisible(true);
                    this.dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "identifiants incorrects");
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdAdmin = new javax.swing.JTextField();
        txtmdpAdmin = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jcombRole = new javax.swing.JComboBox();
        bntConnectAdmin = new javax.swing.JButton();
        btnExitAdmin = new javax.swing.JButton();
        lblErrorAdmin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Rôle");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Identifiant");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 110, -1));
        jPanel1.add(txtIdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 270, -1));
        jPanel1.add(txtmdpAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 270, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mot de passe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 130, -1));

        jcombRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcombRoleActionPerformed(evt);
            }
        });
        jPanel1.add(jcombRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 270, -1));

        bntConnectAdmin.setBackground(new java.awt.Color(0, 51, 51));
        bntConnectAdmin.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        bntConnectAdmin.setForeground(new java.awt.Color(255, 255, 255));
        bntConnectAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        bntConnectAdmin.setText("Se connecter");
        bntConnectAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntConnectAdminActionPerformed(evt);
            }
        });
        jPanel1.add(bntConnectAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 40));

        btnExitAdmin.setBackground(new java.awt.Color(0, 51, 51));
        btnExitAdmin.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        btnExitAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnExitAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnExitAdmin.setText("Quitter");
        btnExitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnExitAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        lblErrorAdmin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblErrorAdmin.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(lblErrorAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 520, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 650, 500));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 38)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 110, 80));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administrateur");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 250, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 110));

        setSize(new java.awt.Dimension(673, 662));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jcombRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcombRoleActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jcombRoleActionPerformed

    private void bntConnectAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntConnectAdminActionPerformed
        // TODO add your handling code here:
        String identfiant = txtIdAdmin.getText();
        String password = txtmdpAdmin.getText();
        String role = String.valueOf(jcombRole.getSelectedItem());
        
        if(identfiant.trim().equals("") || password.trim().equals("")){
            lblErrorAdmin.setText("Veuillez entrez vos identifiants s'il vous plaît ");
        }else{
            verificationUtilisateur(identfiant, password, role);
        }
        
    }//GEN-LAST:event_bntConnectAdminActionPerformed

    private void btnExitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitAdminActionPerformed
        // TODO add your handling code here:
        Index accueil = new Index();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExitAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntConnectAdmin;
    private javax.swing.JButton btnExitAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox jcombRole;
    private javax.swing.JLabel lblErrorAdmin;
    private javax.swing.JTextField txtIdAdmin;
    private javax.swing.JPasswordField txtmdpAdmin;
    // End of variables declaration//GEN-END:variables
}
