/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DBConnection;

/**
 *
 * @author 33760
 */
public class FVisiteur extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;

    /**
     * Creates new form FVisiteur
     */
    
    
    DefaultTableModel model;
    
    public FVisiteur() {
        initComponents();
        setArticlesToTable();
    }

    
    public void setArticlesToTable(){
        try{
            con = DBConnection.getConnection();
            pst = con.prepareStatement("SELECT * FROM article");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String idarticle = rs.getString("idarticle");
                String titre = rs.getString("titreAnnonce");
                String description = rs.getString("descAnnonce");
                Double prixAchatIm = rs.getDouble("prixAchatImme");
                Double prixDep = rs.getDouble("prixDep");
                Double prixRes = rs.getDouble("prixReserve");
                Double fraisPort = rs.getDouble("fraisPort");
                Date dateClo = rs.getDate("dateCloture");
                String pasEnchere = rs.getString("pasEnchere");
                String idVendeur = rs.getString("idvendeur");
                String idRegionLiv = rs.getString("idRegionLiv");
                String idCategorie = rs.getString("idCategorie");
                //String idSouCa = rs.getString("idSousCategorie");
                String etat = rs.getString("etat");
                
                Object[] obj = {idarticle, titre, description, prixAchatIm, prixDep, prixRes, fraisPort, dateClo, pasEnchere, idVendeur,idRegionLiv,idCategorie, etat};
                
                model = (DefaultTableModel)tblArticle.getModel();
                model.addRow(obj);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    public void recherche(String str){
        model = (DefaultTableModel)tblArticle.getModel();
        TableRowSorter<DefaultTableModel>  trs = new TableRowSorter<>(model);
        tblArticle.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enchereEnLignePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("enchereEnLignePU").createEntityManager();
        articleQuery = java.beans.Beans.isDesignTime() ? null : enchereEnLignePUEntityManager.createQuery("SELECT a FROM Article a");
        articleList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : articleQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblArticle.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        tblArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titre", "Description", "Prix Achat immédiat", "Prix Départ", "Prix Réserve", "Frais Port", "Date Clôture", "Pas Enchèere", "Vendeur", "Region Livraison", "Categorie", "Etat"
            }
        ));
        jScrollPane1.setViewportView(tblArticle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 1670, 690));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Rechercher un article");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 300, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("S:aisissez l'article :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 170, -1));

        txtRecherche.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtRecherche.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRechercheKeyReleased(evt);
            }
        });
        jPanel1.add(txtRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, 450, 30));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1550, 60, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1740, 860));

        setBounds(0, 0, 1758, 921);
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechercheKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheKeyReleased
        // TODO add your handling code here:
        String chaineChercher = txtRecherche.getText();
        recherche(chaineChercher);
    }//GEN-LAST:event_txtRechercheKeyReleased

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Index accueil = new Index();
        accueil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVisiteur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVisiteur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<entity.Article> articleList;
    private javax.persistence.Query articleQuery;
    private javax.persistence.EntityManager enchereEnLignePUEntityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticle;
    private javax.swing.JTextField txtRecherche;
    // End of variables declaration//GEN-END:variables
}
